---
- name: ensure cfg directories exist
  become: yes
  file:
    path: '{{ item }}'
    state: directory
    owner: nagios
    group: nagios
  with_items:
    - /usr/local/nagios/etc/hostgroups
    - /usr/local/nagios/etc/hosts
    - /usr/local/nagios/etc/services
  
- name: add nagios.cfg
  become: yes
  template: src=nagios.cfg dest=/usr/local/nagios/etc/nagios.cfg owner=nagios group=nagios backup=no

- name: add nagios contacts
  become: yes
  template: src=contacts.cfg dest=/usr/local/nagios/etc/objects/contacts.cfg owner=nagios group=nagios backup=no

- name: add cgi cfg
  become: yes
  template: src=cgi.cfg dest=/usr/local/nagios/etc/cgi.cfg owner=nagios group=nagios backup=no

- name: add timeperiods.cfg
  become: yes
  template: src=timeperiods.cfg dest=/usr/local/nagios/etc/objects/timeperiods.cfg owner=nagios group=nagios backup=no

- name: add templates.cfg
  become: yes
  template: src=templates.cfg dest=/usr/local/nagios/etc/objects/templates.cfg owner=nagios group=nagios backup=no

- name: add nagios commands
  become: yes
  template: src=commands.cfg dest=/usr/local/nagios/etc/objects/commands.cfg owner=nagios group=nagios backup=no

- name: remove default localhost.cfg
  become: yes
  file: path=/usr/local/nagios/etc/objects/localhost.cfg state=absent

- name: add localhost.cfg
  become: yes
  template: src=localhost.cfg dest=/usr/local/nagios/etc/hosts/localhost.cfg owner=nagios group=nagios backup=no

- name: check nagios config
  become: yes
  shell: /etc/init.d/nagios checkconfig | grep OK
  register: nagios_config_check

- name: check nagios config
  assert:
    that:
      - "'OK' in nagios_config_check.stdout"
