- hosts: nagios
  name: ensure python is installed for ansible
  user: ubuntu
  gather_facts: false
  pre_tasks:
      - name: update apt-get
        raw: sudo apt-get update
      - name: install python for ansible
        raw: sudo apt-get -y install python-simplejson

- hosts: nagios
  name: configure server
  user: ubuntu
  gather_facts: true
  vars:
    project_name: nagios
    keys_to_add:
      - https://github.com/mark-dce.keys
      - https://github.com/little9.keys
      - https://github.com/no-reply.keys
      - https://github.com/bess.keys
      - https://github.com/val99erie.keys
      - https://github.com/jenlindner.keys
    nagios_users:
      - bess
      - mark
      - jamie
      - val
      - tom
      - jen
      - rachel
      - solomon
    db_user: 'db_user'
    db_pass: 'JwuG3CGLYQ1cn6qn'
  roles:
    # - { role: packages }
    # - { role: set_timezone, timezone: America/Chicago }
    # - { role: set_hostname }
    # - { role: sshd_config }
    # - { role: setup_logrotation }
    # - { role: clamav }
    # - { role: pip }
    # - { role: dce_ssl }
    - { role: nagios, nagios_version: '4.3.4' }
    - { role: nrpe, nrpe_version: '3.1.1', nagios_plugins_version: '2.2.1' }
