- hosts: shibboleth_idp
  name: ensure python is installed for ansible
  user: ubuntu
  gather_facts: false
  pre_tasks:
      - name: update apt-get
        raw: sudo apt-get update
      - name: install python for ansible
        raw: sudo apt-get -y install python-simplejson

- hosts: shibboleth_idp
  name: build shibboleth idp server
  user: ubuntu
  gather_facts: true
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    CATALINA_HOME: /var/lib/tomcat8
  vars:
  roles:
    - { role: packages }
    - { role: set_timezone, timezone: America/Chicago }
    - { role: set_hostname }
    - { role: sshd_config }
    - { role: setup_logrotation }
    - { role: pip }
    - { role: dce_ssl }
    - { role: apache_with_mod_ssl }
    - { role: tomcat8 }
    - { role: ldap}
    - { role: shibboleth-idp, idp_version: 3.3.2 }
    - { role: nrpe }
