- hosts: '{{ host }}'
  name: ensure python is installed for ansible
  user: ubuntu
  gather_facts: false
  pre_tasks:
      - name: update apt-get
        raw: sudo apt-get update
      - name: install python for ansible
        raw: sudo apt-get -y install python-simplejson

- hosts: '{{ host }}'
  name: configure server
  user: ubuntu
  gather_facts: true
  vars:
    keys_to_add:
      - https://github.com/mark-dce.keys
      - https://github.com/little9.keys
      - https://github.com/no-reply.keys
      - https://github.com/bess.keys
      - https://github.com/val99erie.keys
      - https://github.com/jenlindner.keys
      - https://github.com/SolomonHD.keys
    db_user: 'db_user'
    db_pass: 'JwuG3CGLYQ1cn6qn'
  roles:
    - { role: packages }
    - { role: capybara-webkit }
    - { role: set_timezone, timezone: America/Chicago }
    - { role: set_hostname, hostname: stage-demo }
    - { role: sshd_config }
    - { role: setup_logrotation }
    - { role: clamav }
    - { role: nrpe, nrpe_version: '3.1.1', nagios_plugins_version: '2.2.1' }
    - { role: ruby, ruby_version: '2.4.2', ruby_sha_256: '93b9e75e00b262bc4def6b26b7ae8717efc252c47154abb7392e54357e6c8c9c' }
    # - { role: ruby, ruby_version: '2.3.4', ruby_sha_256: '98e18f17c933318d0e32fed3aea67e304f174d03170a38fd920c4fbe49fec0c3' }
    - { role: postgres, postgres_pass: 'SlWN30dmREHUJ2Fs' }
    - { role: fedora, fedora_version: '4.7.5' }
    - { role: solr, solr_version: '6.6.2' }
    - { role: pip }
    - { role: fits, fits_version: '0.8.4' }
    - { role: apache, passenger_ver: '5.1.11'}
    - { role: apache_with_mod_ssl }
    - { role: capistrano_setup }
    - { role: dotenv, hostname: stage-demo }
    - { role: sidekiq }
    - { role: imagemagick, imagemagick_ver: '7.0.7', gs_ver: '9.19', openjpg_ver: '2.1.0', libtiff_ver: '4.0.5', libpng_ver: '1.6.28' }
    - { role: ffmpeg, ffmpeg_version: '3.4' }
    # - { role: '{{ host }}' }
    - { role: solr-schema }
    - { role: first_deploy }
    - { role: dce_ssl }
    - { role: force_ssl }
    - { role: restart }
    - { role: splunkuforwarder } #tags: splunk
