defaults: &defaults
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  <<: *defaults
  adapter: postgresql
  database: "<%= ENV['DATABASE_NAME'] %>"
  username: "<%= ENV['DATABASE_USERNAME'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
