# Proxy cantaloupe behind apache

- name: enable mod_proxy_ajp
  become: yes
  command: a2enmod proxy_ajp

- name: enable proxied idp site
  become: yes
  template: src=cantaloupe.conf dest=/etc/apache2/sites-available/cantaloupe.conf backup=yes

- name: enable cantaloupe site
  become: yes
  command: a2ensite cantaloupe

- name: restart apache
  become: yes
  service:
    name: apache2
    enabled: yes
    state: restarted
    
- name: connect tomcat to ajp
  become: yes
  template: src=server.xml dest=$CATALINA_HOME/conf/server.xml owner=tomcat8 group=tomcat8 backup=yes

- name: restart tomcat
  become: yes
  service:
    name: tomcat8
    enabled: yes
    state: restarted

- name: check proxied cantaloupe status
  uri:
    url: "http://{{ hostname}}.{{ domain }}/cantaloupe/iiif"
    return_content: yes
  register: webpage

- fail: msg='cantaloupe is not running as expected'
  when: "'Endpoint' not in webpage.content"
