---
# ROLE: aws_ssm
# roles/aws_ssm/tasks/main.yml
#
# Installs AWS SSM (systems manager) so we can use AWS nightly backups
# Usage:
#    - { role: aws_ssm }

- name: setup install directory
  set_fact:
    install_path: /home/{{ ansible_ssh_user }}/install

- name: ensure install directory exists
  file:
    path: '{{ install_path }}'
    state: directory

- name: download ssm agent package
  get_url: url=https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb dest={{ install_path }}/amazon-ssm-agent.deb

- name: install ssm agent
  become: yes
  shell: cd {{ install_path }} && dpkg -i amazon-ssm-agent.deb

- name: enable ssm system service
  become: yes
  systemd:
    name: amazon-ssm-agent
    enabled: yes

- name: status ssm system service
  become: yes
  systemd:
    name: amazon-ssm-agent
    state: restarted
