---
- name: Check if splunk directory is present
  stat: 
    path: /opt/splunkforwarder
  register: splunk_st

- name: Set fact if splunk exists
  set_fact:
    splunk_exists: true
  when: splunk_st['stat']['exists'] == true

- name: Check if rsyslog is fixed
  slurp:
    src: /etc/rsyslog.conf
  register: rsyslog_contents

- set_fact: 
    syslog: "{{ rsyslog_contents['content'] | b64decode }}"
    
- set_fact: 
    rsyslog_changed: true
  when: "'$PreserveFQDN' in syslog"
