---
- name: Create deploymentclient.conf
  template:
    src: deploymentclient.conf
    dest: /opt/splunkforwarder/etc/system/local
    group: splunk
    owner: splunk

- name: Set inputs.conf
  become: yes
  template:
    src: inputs.conf
    dest: /opt/splunkforwarder/etc/system/local/
    mode: 0664
    group: splunk
    owner: splunk

- name: Set hostname of Forwarder
  become: yes
  lineinfile:
    path: /opt/splunkforwarder/etc/system/local/server.conf
    regexp: '^serverName'
    line: "serverName = {{ [hostname, domain] | join('.') }}\n#hostname is set by the machine's hostname"

- name: Set GUID if selected
  become: yes
  lineinfile:
    path: /opt/splunkforwarder/etc/instance.cfg
    regexp: '.guid'
    line: 'guid = {{ GUID }}'
  when: GUID is defined
