# Put Emory certs into place on the server
---
- name: include ssl vault
  include_vars: emory_ssl.yml

- name: install SSL certificate
  become: yes
  copy:
    content: '{{ ssl_certificate }}'
    dest: /etc/ssl/certs/etd_library_emory_edu_cert.cer
    owner: root
    group: root
    mode: 0644
 
- name: install SSL private key
  become: yes
  copy:
    content: '{{ ssl_private_key }}'
    dest: /etc/ssl/private/etd-multi.key
    owner: root
    group: root
    mode: 0600
    
- name: install SSL ca bundle file
  become: yes
  copy: src=ca-bundle.crt dest=/etc/ssl/certs/ca-bundle.crt
      owner=root
      group=root
      mode=0600
    
- name: re-create apache vhosts file
  become: yes
  template: src=apache_vhost.j2 dest=/etc/apache2/sites-enabled/{{ project_name }}.conf owner=root group=root backup=yes force=yes

- name: restart apache
  become: yes
  service:
    name: apache2
    enabled: yes
    state: restarted
