# The IDP server either:
# 1) needs to have a metadata provider defined for each service 
# provider (shibboleth-sp) which will authenticate
# OR
# 2) to configure relying-party.xml to allow requests from anywhere
# Right now let's go with option #2, and we can move to option #1 if 
# we decide we need greater security --Bess 24 Jan 2018

# - name: copy sp-metadata files
#   become: yes
#   get_url:
#     url: https://paz.curationexperts.com/Shibboleth.sso/Metadata
#     dest: /opt/shibboleth-idp/metadata/sp-metadata.xml
#     force: yes
#     owner: tomcat8
#     group: tomcat8
# 
# If we go with option 1, we'll need a loop for all the sp services in metadata-providers.xml like this:
# <!-- {% for host in sp-hostnames %}
# 
# <MetadataProvider id="{{ host }}-metadata" xsi:type="FileBackedHTTPMetadataProvider"
# metadataURL="https://{{ host }}/Shibboleth.sso/Metadata"
# backingFile="%{idp.home}/metadata/{{ host }}-metadata.xml"/>
# 
# {% endfor %} -->


- name: configure relying-party settings to allow authentication from anywhere
  become: yes
  template: src=relying-party.xml dest=/opt/shibboleth-idp/conf/relying-party.xml owner=tomcat8 group=tomcat8 backup=yes

- name: copy shibboleth2 metadata providers config
  become: yes
  template: src=metadata-providers.xml dest=/opt/shibboleth-idp/conf/metadata-providers.xml owner=tomcat8 group=tomcat8 backup=yes
