---
- name: setup install directory
  set_fact:
    install_path: /opt/install

- name: ensure install directory exists
  become: yes
  file:
    path: '{{ install_path }}'
    state: directory

- name: install nrpe pre-requisites
  package: name={{ item }} state=present
  become: yes
  with_items:
    - libssl-dev
    - xinetd
    - build-essential

- name: create nagios group
  become: yes
  group: name=nagios

- name: create nagios user
  become: yes
  user: name=nagios group=nagios shell=/bin/bash createhome=yes state=present

- name: export LDflags
  become: yes
  shell: export LDFLAGS=-ldl
  when: ansible_distribution == "CentOS"

- name: download plugins
  become: yes
  get_url: url=http://www.nagios-plugins.org/download/nagios-plugins-{{ nagios_plugins_version }}.tar.gz dest=/opt/install/nagios-plugins-{{ nagios_plugins_version }}.tar.gz

- name: untar plugins
  become: yes
  unarchive: src=/opt/install/nagios-plugins-{{ nagios_plugins_version }}.tar.gz dest=/opt/install/ owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} copy=no

- name: configure plugins
  shell: cd /opt/install/nagios-plugins-{{ nagios_plugins_version }} && ./configure --with-nagios-user=nagios --with-nagios-group=nagios

- name: make plugins
  become: yes
  shell: cd /opt/install/nagios-plugins-{{ nagios_plugins_version }} && {{ item }}
  with_items:
    - make
    - make install

- name: download nrpe
  become: yes
  get_url: url=https://sourceforge.net/projects/nagios/files/nrpe-3.x/nrpe-{{ nrpe_version }}/nrpe-{{ nrpe_version }}.tar.gz/download dest=/opt/install/nrpe-{{ nrpe_version }}.tar.gz

- name: untar nrpe
  become: yes
  unarchive: src=/opt/install/nrpe-{{ nrpe_version }}.tar.gz dest=/opt/install/ owner=nagios group=nagios copy=no

- name: configure nrpe
  become: yes
  shell: cd /opt/install/nrpe-{{ nrpe_version }} && ./configure

- name: make nrpe
  become: yes
  shell: cd /opt/install/nrpe-{{ nrpe_version }} && make {{ item }}
  with_items:
    - all
    - install
    - install-plugin
    - install-daemon
    - install-config
    - install-inetd
    # - install-daemon-config # this was needed for v.
    # - install-xinetd

- name: chown /usr/local/nagios
  become: yes
  file: path=/usr/local/nagios group=nagios owner=nagios recurse=yes state=directory

- name: add nagios config to xinetd
  become: yes
  template: src=nrpe_xinetd_config.j2 dest=/etc/xinetd.d/nrpe group=root owner=root

- name: add nrpe checks
  become: yes
  template: src=nrpe_commands_config.j2 group=nagios owner=nagios dest=/usr/local/nagios/etc/nrpe.cfg

- name: add sidekiq check script
  become: yes
  template: src=nrpe_check_sidekiq.j2 group=nagios owner=nagios mode=0755 dest=/usr/local/nagios/libexec/check_sidekiq

- name: ensure event handler directory exists
  become: yes
  file:
    path: '/usr/local/nagios/libexec/event_handlers'
    state: directory
    group: nagios
    owner: nagios
    mode: 0755

- name: add sidekiq event handler
  become: yes
  template: src=restart_sidekiq.j2 group=nagios owner=nagios mode=0755 dest=/usr/local/nagios/libexec/event_handlers/restart_sidekiq

- name: add tomcat7 event handler
  become: yes
  template: src=restart_tomcat7.j2 group=nagios owner=nagios mode=0755 dest=/usr/local/nagios/libexec/event_handlers/restart_tomcat7

- name: add solr event handler
  become: yes
  template: src=restart_solr.j2 group=nagios owner=nagios mode=0755 dest=/usr/local/nagios/libexec/event_handlers/restart_solr

- name: let nagios restart systemctl services
  become: yes
  template: src=nagios_restart.j2 group=root owner=root mode=0755 dest=/etc/sudoers.d/nagios_restart

- name: restart xinetd
  become: yes
  service: name=xinetd state=restarted

- name: try nrpe
  shell: /usr/local/nagios/libexec/check_http www.google.com
  register: google_check

- name: check nrpe output
  assert:
    that:
      - "'HTTP OK' in google_check.stdout"
